### ISSUE TITLE
Documentation improvement for ceylon.test.TestSource?

### ISSUE THREAD

**Issue by loldrup** [ceylon/ceylon-lang.org#488] opened 2017-09-10 23:04 UTC
When looking at these two definitions:

https://modules.ceylon-lang.org/repo/1/ceylon/test/1.3.3.1/module-doc/api/index.html#createTestRunner

https://modules.ceylon-lang.org/repo/1/ceylon/test/1.3.3.1/module-doc/api/index.html#TestSource

I saw that I could pass a `FunctionDeclaration` value to the `createTestRunner` function.

Unfortunately, the signature for `TestSource` contained no further link to the specific `FunctionDeclaration` definition it was referring to. Thus I instead tried to find the definition on my own, by searching through herd.ceylon-lang.org.
This led me to find this declaration:

https://modules.ceylon-lang.org/repo/1/ceylon/ast/core/1.3.2/module-doc/api/FunctionDeclaration.type.html

Which then led me down a long path of wrongness. After a lot of work to make such a type declaration for my test function, I finally passed it on to createTestRunner, only to have it tell me that it didn't work. Then a nice guy on stackoverflow told me that `TestSource` had actually referred to some other definition of `FunctionDeclaration` (Question: [Creating a ceylon.test.TestRunner](https://stackoverflow.com/questions/46145157/creating-a-ceylon-test-testrunner/46145400#46145400)).

Would it be possible for the documentation for `TestSource` to link straight to the right definition of `FunctionDeclaration`, such that one doesn't inadvertently find the wrong definition?

**Comment by gavinking** [comment] 2017-09-11 11:22
The actual issue here is that 'ceylon doc' was run without links back to the language module when compiling the docs for the `ceylon.test` 1.3.3.1 fix. (cc @FroMage.) You can see that the problem doesn't affect the docs for 1.3.3 here, which were compiled via the regular build process:

<https://modules.ceylon-lang.org/repo/1/ceylon/test/1.3.3/module-doc/api/index.html#TestSource>

So I think the problem is a one-off and I can close this issue.

PS @loldrup, this problem would *never* have happened if you were writing your code in an IDE ;-)

**Closed by gavinking** 2017-09-11 11:22 UTC

**Comment by loldrup** [comment] 2017-09-11 12:08
But I *am* writing and running my code in an IDE! (IntelliJ IDE with Ceylon
plugin).

The issue has not been solved on my side: I still get the runtime error
whenever I add a new code line in run.ceylon. And it still goes away on the
second click on the second click on the green 'run' button.

Den 11. sep. 2017 1.22 PM skrev "Gavin King" <notifications@github.com>:

**Comment by loldrup** [comment] 2017-09-11 12:11
Sorry, I confused two issues!

(but I'm curious how the IDE could have avoided the confusion. I must have
overlooked some hint?)

Mvh. Jon Loldrup

**Comment by gavinking** [comment] 2017-09-11 12:35
@loldrup If you would have clicked on the definition of `TestSource`, and, from there, navigated to the definition of `FunctionDeclaration`, it would have taken you to the right one.

**Comment by lucaswerkmeister** [comment] 2017-09-11 12:51
> it would have taken you to the right one.

Although its documentation doesn’t mention the `` `function x` `` syntax…

**Comment by loldrup** [comment] 2017-09-11 13:39
I've just discovered the (Go To -> Declaration) option in the right click
menu of names occuring in source code.
Is this what you are referring to?

Using this feature, I walked from my calling of the 'createTestRunner'
function to the definition of this function and from there to the
definition of TestSource and from there to the definition of
FunctionDeclaration.
Looking at the breadcrumbs I can see that that definition belongs to
'ceylon.language.meta.declaration', so you're right, I could have realised
that it didn't belong to 'ceylon.ast.core'.

But then I would still have to figure out how to make an object of type
'FunctionDeclaration'. FunctionDeclaration is just an interface, so should
I then create my own class implementing that interface?
How should I approach finding the answer to such a question?
If I search for "FunctionDeclaration" on Herd, nothing shows up.
I guess I could have simply searched Herd for the first step in the
breadcrumb path: "language", and then walk down to the breadcrumb path
manually until FunctionDeclaration shows up (it's actually listed straight
in the members list of the language module - nice).
But then, finally finding it, it says nothing about how one creates such a
thing. It is still, after all, just an interface.
So what would a veteran Ceylon user then do in that situation?

Den 11. sep. 2017 2.35 PM skrev "Gavin King" <notifications@github.com>:

**Comment by gavinking** [comment] 2017-09-11 14:00
@loldrup The metamodel is a language feature documented [here](https://ceylon-lang.org/documentation/current/tour/annotations/#the_metamodel) and [here](https://ceylon-lang.org/documentation/1.3/spec/html/expressions.html#metamodelexpressions).
